test_msdscript: main.cpp test_msdscript.cpp test_msdscript.hpp exec.cpp exec.h test_Cmdline.hpp test_Cmdline.cpp
	c++ --std=c++14 -O2 -o test_msdscript main.cpp test_msdscript.cpp exec.cpp test_Cmdline.cpp
